--liquibase formatted sql
--changeset szczesnaj:1
CREATE TABLE CUSTOMER
(
    id      BIGINT AUTO_INCREMENT  PRIMARY KEY UNIQUE,
    PESEL_NUMBER   VARCHAR(11) NOT NULL UNIQUE,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(40) NOT NULL
);

CREATE TABLE COMMUNICATION_METHODS
(
    id      BIGINT AUTO_INCREMENT  PRIMARY KEY UNIQUE,
    EMAIL_ADDRESS   VARCHAR(40),
    RESIDENCE_ADDRESS VARCHAR(150),
    REGISTERED_ADDRESS VARCHAR(150),
    PRIVATE_PHONE_NUMBER VARCHAR(11),
    BUSINESS_PHONE_NUMBER VARCHAR(11)
);
