--liquibase formatted sql
--changeset szczesnaj:1
CREATE TABLE CUSTOMER
(
    id      BIGINT AUTO_INCREMENT  PRIMARY KEY,
    EMAIL   VARCHAR(40),
    RESIDENCE_ADDRESS VARCHAR(150),
    REGISTERED_ADDRESS VARCHAR(150),
    PRIVATE_PHONE VARCHAR(11),
    BUSINESS_PHONE VARCHAR(11)
);
