insert into customer(name, surname, pesel_number) values ('Mieszko 1', 'Kowalski 1', '42040200001');
insert into customer(name, surname, pesel_number) values ('Mieszko 2', 'Kowalski 2', '42040200002');
insert into customer(name, surname, pesel_number) values ('Mieszko 3', 'Kowalski 3', '42040200003');
insert into customer(name, surname, pesel_number) values ('Mieszko 4', 'Kowalski 4', '42040200004');
insert into customer(name, surname, pesel_number) values ('Mieszko 5', 'Kowalski 5', '42040200005');
insert into customer(name, surname, pesel_number) values ('Mieszko 6', 'Kowalski 6', '42040200006');
insert into customer(name, surname, pesel_number) values ('Mieszko 7', 'Kowalski 7', '42040200007');
insert into customer(name, surname, pesel_number) values ('Mieszko 8', 'Kowalski 8', '42040200008');
insert into customer(name, surname, pesel_number) values ('Mieszko 9', 'Kowalski 9', '42040200009');
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (1, 'email@address 1', 'residence_address 1', 'registered_address 1',  'priva_num 1', 'busin_num 1' );
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (2, 'email@address 2', 'residence_address 2', 'registered_address 2',  'priva_num 2', 'busin_num 2' );
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (3, 'email@address 3', 'residence_address 3', 'registered_address 3',  'priva_num 3', 'busin_num 3' );
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (4, 'email@address 4', 'residence_address 4', 'registered_address 4',  'priva_num 4', 'busin_num 4' );
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (5, 'email@address 5', 'residence_address 5', 'registered_address 5',  'priva_num 5', 'busin_num 5' );
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (6, 'email@address 6', 'residence_address 6', 'registered_address 6',  'priva_num 6', 'busin_num 6' );
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (7, 'email@address 7', 'residence_address 7', 'registered_address 7',  'priva_num 7', 'busin_num 7' );
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (8, 'email@address 8', 'residence_address 8', 'registered_address 8',  'priva_num 8', 'busin_num 8' );
insert into communication_methods(customer_id, email_address, residence_address, registered_address, private_phone_number, business_phone_number) values (9, 'email@address 9', 'residence_address 9', 'registered_address 9',  'priva_num 9', 'busin_num 9' );
